name: Automated API tests using Postman CLI

on:
  workflow_dispatch:

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"
      - name: Install newman
        run: |
          npm install -g newman
      - name: Run POSTMAN collection
        run: |
          newman run __tests__/integration/tokyopickup-v2.postman_collection.json --env-var "base-url=${{ secrets.BASE_URL }}"
